# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: pygments
markdown: kramdown


defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Voices in my head

description: Just another blog.
author:
  name: Nicolas Corrarello
  email: nicolas@corrarello.com
  github: ncorrare
  linkedin: ncorrare
  bio: Musings of an electronic cigarette smoking man.
  email_md5: 9ec955f0cb65381eae42566d4351a8b5

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH:
